import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import { SuperadminShell } from "./SuperadminShell";

export function SuperadminPlansPage() { const [plans,setPlans]=useState<any[]>([]); useEffect(()=>{supabase.from("subscription_plans").select("*").order("monthly_price").then(({data})=>setPlans(data??[]));},[]); return <SuperadminShell title="Planes" description="Catálogo comercial SaaS de Medin."><div className="grid gap-4 lg:grid-cols-5">{plans.map(plan=><div key={plan.id} className="rounded-lg border border-clinic-line bg-white p-4"><p className="font-semibold">{plan.name}</p><p className="mt-2 text-xl font-semibold">${Number(plan.monthly_price).toLocaleString("es-AR")}</p><p className="text-sm text-clinic-muted">Setup ${Number(plan.setup_price??0).toLocaleString("es-AR")}</p><p className="mt-3 text-sm">{plan.max_professionals??"∞"} profesionales · {plan.max_users??"∞"} usuarios</p><p className="mt-2 text-xs text-clinic-muted">{plan.active?"Activo":"Inactivo"}{plan.recommended?" · Recomendado":""}</p></div>)}</div></SuperadminShell>; }
export function SuperadminSubscriptionsPage() {
  const [subscriptions,setSubscriptions]=useState<any[]>([]); const [requests,setRequests]=useState<any[]>([]); const [error,setError]=useState("");
  async function load() { const [subs, pending] = await Promise.all([supabase.from("clinic_subscriptions").select("*, clinics(name,slug), subscription_plans(name)").order("updated_at",{ascending:false}),supabase.from("plan_change_requests").select("id,status,created_at, clinics(name), requested_plan:subscription_plans!plan_change_requests_requested_plan_id_fkey(name), current_plan:subscription_plans!plan_change_requests_current_plan_id_fkey(name), profiles!plan_change_requests_requested_by_fkey(full_name)").eq("status","pending").order("created_at",{ascending:false})]); if(subs.error) throw subs.error; if(pending.error) throw pending.error; setSubscriptions(subs.data??[]); setRequests(pending.data??[]); }
  useEffect(()=>{load().catch((err)=>setError(err instanceof Error?err.message:"No pudimos cargar suscripciones."));},[]);
  return <SuperadminShell title="Suscripciones" description="Estado comercial, vencimientos y solicitudes SaaS.">{error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<h2 className="mb-3 text-lg font-semibold">Solicitudes pendientes</h2><div className="mb-6 overflow-hidden rounded-lg border border-clinic-line bg-white">{requests.map(item=><div key={item.id} className="grid gap-2 border-b border-clinic-line px-4 py-3 md:grid-cols-5"><p className="font-semibold">{item.clinics?.name}</p><p>{item.current_plan?.name??"Sin plan"}</p><p>{item.requested_plan?.name??"Plan solicitado"}</p><p className="text-sm text-clinic-muted">{new Date(item.created_at).toLocaleDateString("es-AR")}</p><p className="text-sm text-amber-700">Pending · {item.profiles?.full_name??"Equipo clínica"}</p></div>)}{!requests.length&&<p className="p-5 text-sm text-clinic-muted">No hay solicitudes pendientes.</p>}</div><h2 className="mb-3 text-lg font-semibold">Suscripciones activas</h2><div className="overflow-hidden rounded-lg border border-clinic-line bg-white">{subscriptions.map(item=><div key={item.id} className="grid gap-2 border-b border-clinic-line px-4 py-3 md:grid-cols-4"><p className="font-semibold">{item.clinics?.name}</p><p>{item.subscription_plans?.name??"Sin plan"}</p><p className="text-sm text-clinic-muted">{item.status}</p><p className="text-sm text-clinic-muted">Vence: {item.current_period_end?new Date(item.current_period_end).toLocaleDateString("es-AR"):"A confirmar"}</p></div>)}{!subscriptions.length&&<p className="p-6 text-sm text-clinic-muted">Sin suscripciones.</p>}</div></SuperadminShell>;
}
